### ISSUE TITLE
suggestion - automatically get repo list from the aur...

### ISSUE THREAD

**Issue by johnlane** [amiad/aur2aur4#2]
Here's a suggestion... I used your script with the following command-line to pull the repo list from the AUR.

```
 ssh aur@aur4.archlinux.org list-repos | grep '^*' | sed -e 's/^*//' | xargs -n1 ./aur2aur4.sh
```

It gets the empty repos (those marked with a `*` prefix) and runs the script on each one. Worked a treat for me. Thanks for the script!

**Comment by amiad** [comment]
I added option to get empty repos list and import the packages from aur3.
thanks.
