### ISSUE TITLE
Doesn't work with split packages

### ISSUE THREAD

**Issue by SanskritFritz** [amiad/aur2aur4#5]
I'm not sure, but maybe if you fetched the package base name, it would work?

**Comment by amiad** [comment]
I not understand your question.

**Comment by SanskritFritz** [comment]
Sorry for that. A split package is a package that uses a package base name but provides more packages under different names. An example is [pzl_games](https://aur.archlinux.org/pkgbase/pzl_games/) but you won't find it if you list the packages by user. The packages provided are for example [pzl_common](https://aur.archlinux.org/packages/pzl_common/) or [pzl_minesweeper](https://aur.archlinux.org/packages/pzl_minesweeper/) are listed by user. So if you fetch the base name of a package instead of just the name, the script would find all split packages as well. That means you have to follow each package link and read the base name.

**Comment by amiad** [comment]
OK.
If I will use "PackageBase" instead "Name" then the problem will solved?

**Comment by SanskritFritz** [comment]
I think so, yes.

**Comment by SanskritFritz** [comment]
Nice, thanks!
